#!/usr/bin/env node
// Generate a framework-calibration report for the profile currently loaded in
// the running Vantage app: value-chain positioning + ability core, written to
// validation/report-<label>-<date>.md with the debrief questionnaire appended.
//
// Usage:  node scripts/framework-report.mjs --label subject-a [--jd <jdSessionId>] [--web]
// Prereq: the dev server is running against the subject's profile, e.g.
//         VANTAGE_DB=validation/subject-a.sqlite npm run dev
//
// Protocol & success criteria: docs/validation-protocol.md

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const BASE = process.env.VANTAGE_URL ?? 'http://localhost:3000';
const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? undefined : (args[i + 1]?.startsWith('--') ? true : (args[i + 1] ?? true));
};
const label = typeof flag('label') === 'string' ? flag('label') : 'subject';
const jdSessionId = typeof flag('jd') === 'string' ? flag('jd') : undefined;
const useWebSearch = args.includes('--web');

async function runMode(mode) {
  process.stdout.write(`Running ${mode}… `);
  const res = await fetch(`${BASE}/api/ai/paths`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ mode, jdSessionId, useWebSearch }),
  });
  if (!res.ok) throw new Error(`${mode} failed (${res.status}): ${(await res.text()).slice(0, 300)}`);
  const text = await res.text(); // plain-text stream, collected whole
  console.log(`done (${text.length} chars)`);
  return text.trim();
}

const health = await fetch(`${BASE}/api/entries`).then((r) => r.json()).catch(() => null);
if (!health || !Array.isArray(health) || health.length === 0) {
  console.error(`No entries found at ${BASE}. Is the dev server running against the subject's profile?\n  VANTAGE_DB=validation/${label}.sqlite npm run dev`);
  process.exit(1);
}
console.log(`Profile loaded: ${health.length} entries. Generating report for "${label}"…`);

const valueChain = await runMode('value-chain');
const abilityCore = await runMode('ability-core');

const date = new Date().toISOString().slice(0, 10);
const report = `# Career calibration report — ${label} (${date})

> Generated by Vantage from ${health.length} experience entries you provided.
> Two lenses: where your evidence places you on your industry's value chain, and
> what your capability structure (knowledge / skills / strengths) looks like.
> Everything here is grounded in your entries — where evidence was insufficient,
> the analysis says so. Strengths are stated as hypotheses for YOU to confirm.

---

# Lens 1 · Value-chain positioning

${valueChain}

---

# Lens 2 · Ability core (knowledge – skills – strengths)

${abilityCore}

---

# Debrief (interviewer: record answers verbatim)

1. 哪一句話讓你想到之前沒想過的事？是哪一句？
2. 這份分析會改變你未來三個月的任何決定嗎？具體是什麼決定？
3. 哪部分你覺得是廢話、或像算命？
4. 比起把履歷貼進 ChatGPT 問建議，這份差在哪？
5. 你願意為這個付費或推薦給朋友嗎？（1–10，為什麼）

Interviewer notes:
- Strengths hypotheses confirmed / rejected by subject:
- Reaction score (1 = polite interest, 5 = named a concrete decision change):
`;

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'validation');
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, `report-${label}-${date}.md`);
writeFileSync(outPath, report);
console.log(`\nReport written: validation/report-${label}-${date}.md`);
